const express = require('express');
const cors = require('cors');
const path = require('path');
const fs = require('fs');
const archiver = require('archiver');

const app = express();
const PORT = 3000;

app.use(cors());
app.use(express.json());

app.use(express.static(path.join(__dirname, '../frontend')));

const availableComponents = [

    {
        id: 1,
        name: 'Response Handler',
        file: 'response_handler.py',
        description: 'Handles chatbot responses based on user input.'
    },
    {
        id: 2,
        name: 'Logger',
        file: 'logger.py',
        description: 'Logs all conversation history to a file'
    },
    {
        id: 3,
        name: 'Data Processor',
        file: 'data_processor.py',
        description: 'Processes and validates user input data'
    }
];

app.get('/api/components', (req, res) => {
    res.json({
        success: true,
        components: availableComponents
    });
});

app.post('/api/build', (req, res) => {
    const { components: selectedIds } = req.body;
    if (!selectedIds || selectedIds.length === 0) {
        return res.status(400).json({
            success: false,
            error: 'No components selected'
        });
    }

    // Normalizar ids a números (por si vienen como strings) y usar la variable correcta
    const selectedIdsNums = selectedIds.map(id => Number(id));
    const selectedComponents = availableComponents.filter(c => selectedIdsNums.includes(Number(c.id)));

    if (selectedComponents.length === 0) {
        return res.status(400).json({
            success: false,
            error: 'Invalid component IDs'
        });
    }

    const timestamp = new Date().toISOString().replace(/[:.]/g, '-').slice(0, -5);
    const zipFileName = `chatbot-package-${timestamp}.zip`;

    res.attachment(zipFileName);
    res.setHeader('Content-Type', 'application/zip');

    //Es para crear el archivo
    const archive = archiver('zip', {
        zlib: { level: 9 }
    });


    //Manejo de errores
    archive.on('error', (err) => {
        console.error('Archive error:', err);
        if (!res.headersSent) {
            res.status(500).json({
                success: false,
                error: 'Error creating ZIP file'
            });
        } else {
            // cerrar la respuesta si ya empezó a enviarse
            res.destroy(err);
        }
    });

    archive.pipe(res);

    const componentsPath = path.join(__dirname, '../components');
    selectedComponents.forEach(comp => {
        const filePath = path.join(componentsPath, comp.file);
        if (fs.existsSync(filePath)) {
            archive.file(filePath, { name: `components/${comp.file}` });
        }

    });

    const readmeContent = generateReadme(selectedComponents);
    archive.append(readmeContent, { name: 'README.txt' });

    const shellScript = generateShellScript(selectedComponents);
    archive.append(shellScript, { name: 'run.sh', mode: 0o755 });

    const batchScript = generateBatchScript(selectedComponents);
    archive.append(batchScript, { name: 'run.bat' });

    archive.finalize();

});

/// FUNCION PARA GENERAR README.md
function generateReadme(components) {
    const componentList = components.map(c => `- **${c.name}** (${c.file}): ${c.description}`).join('\n');

    return `# Chatbot Components Package

## Package Information
- **Created:** ${new Date().toLocaleString()}
- **Number of Components:** ${components.length}

## Included Components
${componentList}

## Setup Instructions

### Prerequisites
- Python 3.7 or higher
- Terminal/Command Prompt access

### Installation

#### For Linux/Mac:
1. Extract this ZIP file to your desired location
2. Open terminal in the extracted folder
3. Make the run script executable:
   \`\`\`bash
   chmod +x run.sh
   \`\`\`
4. Run the chatbot:
   \`\`\`bash
   ./run.sh
   \`\`\`

#### For Windows:
1. Extract this ZIP file to your desired location
2. Open Command Prompt in the extracted folder
3. Run the chatbot:
   \`\`\`cmd
   run.bat
   \`\`\`

### Running Individual Components

You can also run each component individually to test:

\`\`\`bash
python3 components/response_handler.py
python3 components/logger.py
python3 components/data_processor.py
\`\`\`

## Component Descriptions

${components.map(c => `### ${c.name}
- **File:** \`${c.file}\`
- **Purpose:** ${c.description}
`).join('\n')}

## Troubleshooting

**Issue:** "python3: command not found"
- **Solution:** Try using \`python\` instead of \`python3\`, or install Python 3

**Issue:** Permission denied (Linux/Mac)
- **Solution:** Run \`chmod +x run.sh\` to make the script executable

**Issue:** Scripts don't run on Windows
- **Solution:** Make sure you're running from Command Prompt, not PowerShell

## Support
For issues or questions, please contact the development team.

---
*Generated by Mini Chatbot Workspace*
`;
}

// Función para generar script shell (Linux/Mac)
function generateShellScript(components) {
    const componentFiles = components.map(c => c.file).join(' ');

    return `#!/bin/bash

# Chatbot Runner Script for Linux/Mac
# Generated: ${new Date().toLocaleString()}

echo "======================================"
echo "  CHATBOT COMPONENTS RUNNER"
echo "======================================"
echo ""

# Check if Python 3 is installed
if ! command -v python3 &> /dev/null
then
    echo "Error: Python 3 is not installed"
    echo "Please install Python 3 to run this chatbot"
    exit 1
fi

echo "Python version:"
python3 --version
echo ""

# Run each component
${components.map(c => `
echo "Running ${c.name}..."
python3 components/${c.file}
echo ""
`).join('')}

echo "======================================"
echo "  All components executed successfully!"
echo "======================================"
`;
}

// Función para generar script batch (Windows)
function generateBatchScript(components) {
    return `@echo off
REM Chatbot Runner Script for Windows
REM Generated: ${new Date().toLocaleString()}

echo ======================================
echo   CHATBOT COMPONENTS RUNNER
echo ======================================
echo.

REM Check if Python is installed
python --version >nul 2>&1
if %errorlevel% neq 0 (
    echo Error: Python is not installed
    echo Please install Python 3 to run this chatbot
    pause
    exit /b 1
)

echo Python version:
python --version
echo.

REM Run each component
${components.map(c => `
echo Running ${c.name}...
python components\\${c.file}
echo.
`).join('')}

echo ======================================
echo   All components executed successfully!
echo ======================================
echo.
pause
`;
}

app.get('/api/health', (req, res) => {
    res.json({ status: 'Server is running!' });
});

app.listen(PORT, () => {
    console.log(`🚀 Server running on http://localhost:${PORT}`);
    console.log(`📦 API available at http://localhost:${PORT}/api/components`);
    console.log(`🔨 Build endpoint: http://localhost:${PORT}/api/build`);
})